#+TITLE: Complementary Filters Shaping Using $\mathcal{H}_\infty$ Synthesis
:DRAWER:
#+SUBTITLE: Dehaeze Thomas, Verma Mohit and Collette Christophe
#+OPTIONS: toc:nil
#+OPTIONS: html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/readtheorg.css"/>
#+HTML_HEAD: <script src="js/jquery.min.js"></script>
#+HTML_HEAD: <script src="js/bootstrap.min.js"></script>
#+HTML_HEAD: <script src="js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script src="js/readtheorg.js"></script>
:END:

#+begin_quote
  *Abstract*:

  For many applications, large bandwidth and dynamic ranges are requiring to use several sensors, whose signals are combined using complementary filters.
  This paper presents a method for designing these complementary filters using $\mathcal{H}_\infty$ synthesis that allows to shape the filter norms.
  This method is shown to be easily applicable for the synthesis of complex complementary filters.
#+end_quote

* Paper ([[file:paper/paper.pdf][link]])
:PROPERTIES:
:UNNUMBERED: t
:END:
The paper has been created [[https://orgmode.org/][Org Mode]] (generating [[https://www.latex-project.org/][LaTeX]] code) under [[https://www.gnu.org/software/emacs/][Emacs]].

* Matlab Scripts ([[file:matlab/index.org][link]])
:PROPERTIES:
:UNNUMBERED: t
:END:
All the [[https://fr.mathworks.com/][Matlab]] code that was used for the paper are accessible so that all the results are reproducible.

* Tikz Figures ([[file:tikz/index.org][link]])
:PROPERTIES:
:UNNUMBERED: t
:END:
All the figures for the paper have been generated using [[https://sourceforge.net/projects/pgf/][TikZ]].

* Poster ([[file:poster/poster.pdf][link]])
:PROPERTIES:
:UNNUMBERED: t
:END:
The poster has been created using the [[https://www.ctan.org/pkg/tikzposter][tikzposter]] package for [[https://sourceforge.net/projects/latex-beamer/][beamer]].

* Presentation ([[file:presentation/presentation.pdf][link]])
:PROPERTIES:
:UNNUMBERED: t
:END:
The presentation for the [[http://iccma.org/][ICCMA 2019]] conference has been created using the [[https://github.com/josephwright/beamer][beamer]] package.

* How to cite this paper
:PROPERTIES:
:UNNUMBERED: t
:END:
To cite this paper use the following bibtex code.
#+begin_src bibtex
@inproceedings{dehaeze19_compl_filter_shapin_using_synth,
  author =       {Thomas Dehaeze and Mohit Vermat and Christophe Collette},
  title =        {Complementary Filters Shaping Using $\mathcal{H}_\infty$
                  Synthesis},
  booktitle =    {ICCMA'19},
  year =         2019,
  language =     {english},
}
#+end_src

You can also use the formatted citation below.
#+begin_quote
  Dehaeze, T., Vermat, M., & Collette, C., Complementary filters shaping using $H_\infty$ synthesis, In , ICCMA'19 (pp. ) (2019). : .
#+end_quote
