#+TITLE: Design of Complementary Filters Using the $\mathcal{H}_\infty$ Synthesis
:DRAWER:
#+LATEX_CLASS: ieeeconf
#+LATEX_CLASS_OPTIONS: [letterpaper, 10 pt, conference]
#+OPTIONS: toc:nil todo:nil
#+STARTUP: overview

#+DATE: {{{time(%Y-%m-%d)}}}
#+AUTHOR: @@latex:Dehaeze Thomas$^{1}$, Verma Mohit$^{2}$ and Collette Christophe$^{3}$ @@
#+AUTHOR: @@latex:\thanks{$^{1}$Dehaeze Thomas {\tt\small thomas.dehaeze@esrf.fr}}@@
#+AUTHOR: @@latex:\thanks{$^{2}$Vermat Mohit {\tt\small mohit.verma@ulb.ac.be}}@@
#+AUTHOR: @@latex:\thanks{$^{3}$Collette Christophe {\tt\small ccollett@ulb.ac.be}}@@

#+LATEX_HEADER: \usepackage{amsmath,amssymb,amsfonts, cases}
#+LATEX_HEADER: \usepackage[noadjust,space,compress]{cite}
# #+LATEX_HEADER: \usepackage{showframe}
#+LATEX_HEADER: \usepackage{algorithmic, graphicx, textcomp}
#+LATEX_HEADER: \usepackage{xcolor, import, hyperref}
#+LATEX_HEADER: \usepackage[USenglish]{babel}
#+LATEX_HEADER: \setcounter{footnote}{1}
#+LATEX_HEADER: \input{config.tex}
#+LATEX_HEADER: \renewcommand{\citedash}{--}
#+LATEX_HEADER: \IEEEoverridecommandlockouts

\bibliographystyle{IEEEtran}
:END:

* LaTeX Config                                                     :noexport:
#+begin_src latex :tangle config.tex
  % H Infini
  \newcommand{\mathcal{H}_\infty}{\mathcal{H}_\infty}

  % H 2
  \newcommand{\htwo}{\mathcal{H}_2}

  % Omega
  \newcommand{\w}{\omega}

  % H-Infinity Norm
  \newcommand{\hnorm}[1]{\left\|#1\right\|_{\infty}}

  % H-2 Norm
  \newcommand{\normtwo}[1]{\left\|#1\right\|_{2}}

  % Norm
  \newcommand{\norm}[1]{\left\|#1\right\|}

  % Absolute value
  \newcommand{\abs}[1]{\left\lvert #1 \right\lvert}

  % Minimum Subscript
  \newcommand{\smin}{_{\text{min}}}

  % Maximum Subscript
  \newcommand{\smax}{_{\text{max}}}

  \newcommand*\colvec[1]{\begin{bmatrix}#1\end{bmatrix}}
#+end_src

* Build                                                            :noexport:
#+BEGIN_SRC emacs-lisp :results none
  (add-to-list 'org-latex-classes
               '("ieeeconf"
                 "\\documentclass{ieeeconf}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
#+END_SRC

#+BEGIN_SRC emacs-lisp :results none
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                                      'comment 'identity))
          do
          (setf (buffer-substring (org-element-property :begin comment)
                                  (org-element-property :end comment))
                "")))

  ;; add to export hook
  (add-hook 'org-export-before-processing-hook 'delete-org-comments)
#+END_SRC

* Abstract                                                           :ignore:
#+begin_abstract
  Abstract text to be done
#+end_abstract

* Introduction
  <<sec:introduction>>

*** DONE Establish the importance of the research topic            :ignore:
CLOSED: [2019-08-17 sam. 23:34]
# What are Complementary Filters
A set of filters is said to be complementary if the sum of their transfer functions is equal to one at all frequencies.
These filters are used when two of more sensors are measuring the same physical quantity with different noise characteristics. Unreliable frequencies of each sensors are filtered out by the complementary filters and combined to form a "super sensor" giving a better estimate of the physical quantity over a wider bandwidth.
This technique is called sensor blending or sensor fusion and used for many applications.\par

*** DONE Applications of complementary filtering                   :ignore:
CLOSED: [2019-08-18 dim. 14:21]
# Improve bandwidth for UAV
In cite:zimmermann92_high_bandw_orien_measur_contr,corke04_inert_visual_sensin_system_small_auton_helic,min15_compl_filter_desig_angle_estim, such technique is used for the attitude estimation of Unmanned Aerial Vehicles (UAV) using various sensors (accelerometers, gyroscopes, vision sensors, ...).
# Improving the control robustness
In cite:collette15_sensor_fusion_method_high_perfor, several sensor fusion configurations using different types of sensors (inertial, relative motion and force) have been discussed in order to increase the control bandwidth of active vibration isolation systems.
# Merging of different sensor types
Furthermore, sensor fusion is used for the low frequency isolation at the Laser Interferometer Gravitational-Wave Observator (LIGO), where inertial sensors are merged with relative sensors
cite:matichard15_seism_isolat_advan_ligo,hua04_polyp_fir_compl_filter_contr_system. \par

*** DONE Current design methods for complementary filters          :ignore:
CLOSED: [2019-08-18 dim. 15:38]
# Why Design of Complementary Filter is important
As the super sensor noise characteristics depends largely on the complementary filter norms, their proper design is of primary importance for sensor fusion performance.
# Discuss the different approach to complementary filter design
Different design methods have been developed.
In cite:corke04_inert_visual_sensin_system_small_auton_helic,jensen13_basic_uas,min15_compl_filter_desig_angle_estim, analytical formulas for complementary filter transfer functions of first and second order have been proposed.
# Third Order and Higher orders
Higher order complementary filters have been used in
cite:shaw90_bandw_enhan_posit_measur_using_measur_accel,zimmermann92_high_bandw_orien_measur_contr,collette15_sensor_fusion_method_high_perfor.
# Alternate Formulation
In cite:jensen13_basic_uas, the sensitivity and complementary sensitivity transfer functions of a feedback architecture have been proposed to be used for complementary filters. The design of such filters can then benefits from the developments of classical control theory.
# LMI / convex Optimization
Linear Matrix Inequalities (LMIs) are used in cite:pascoal99_navig_system_desig_using_time for the synthesis of complementary filters satisfying some frequency-like performance.
# Least Square method for finding the optimal filter coefficients
A design method using linear least squares to optimize the coefficients of complementary filters is proposed in cite:min15_compl_filter_desig_angle_estim.
# FIR Filters
Finally, high order Finite Impulse Response (FIR) complementary filters are used to merge sensors at LIGO cite:hua05_low_ligo,hua04_polyp_fir_compl_filter_contr_system,matichard15_seism_isolat_advan_ligo. The synthesis of such filter using convex optimization is presented in cite:hua05_low_ligo. \par

*** Describe a gap in the research                                 :ignore:
# There is a need for easy synthesis methods for complementary filters
Although many design methods of complementary filters have been proposed

We believe that none

It lacks a method of designing complementary filters

*** Describe the paper itself / the problem which is addressed     :ignore:
In this paper, we propose a synthesis method for the shaping of complementary filters using the $\mathcal{H}_\infty$ norm.\\

*** DONE Introduce Each part of the paper                          :ignore:
CLOSED: [2019-08-17 sam. 15:28]
The section ref:sec:requirements gives a brief overview of sensor fusion using complementary filters and the associated requirements on their norms.
In section ref:sec:hinf_method, a new method for designing complementary filters using the $\mathcal{H}_\infty$ synthesis is proposed.
In section ref:sec:application_ligo, two high order complementary filters are designed using the proposed method and compared with FIR filters used for sensor fusion at the LIGO.
Our conclusions are drawn in the final section.

* Complementary Filters Requirements
<<sec:requirements>>

** Introduction                                                     :ignore:
As stated in the Introduction, complementary filters are widely used for the fusion of two sensors.

** Sensor Fusion Architecture
<<sec:sensor_fusion>>

Let's consider two sensors measuring the same physical quantity $x$ but with different dynamics ($G_1(s)$ and $G_2(s)$) and noise characteristics ($n_1$ and $n_2$).

The signals from both sensors are fed into two complementary filters $H_1(s)$ and $H_2(s)$ and then combined to yield an estimate $\hat{x}$ of $x$ as shown on Fig. ref:fig:fusion_two_noisy_sensors_with_dyn_ter:
#+NAME: eq:comp_filter_estimate
\begin{equation}
  \hat{x} = \left(G_1 H_1 + G_2 H_2\right) x + H_1 n_1 + H_2 n_2
\end{equation}

#+name: fig:fusion_two_noisy_sensors_with_dyn_ter
#+caption: Sensor Fusion Architecture
#+attr_latex: :scale 1
[[file:figs/fusion_two_noisy_sensors_with_dyn_ter.pdf]]

Filters $H_1(s)$ and $H_2(s)$ are said to be complementary if their transfer function sum is equal to one at all frequencies:
#+NAME: eq:comp_filter
\begin{equation}
  H_1(s) + H_2(s) = 1
\end{equation}

** Noise Sensor Filtering
<<sec:noise_filtering>>

If we now consider sensors with perfect dynamics ($G_1(s) = G_2(s) = 1$), the estimate $\hat{x}$ becomes
#+NAME: eq:estimate_perfect_dyn
\begin{equation}
  \hat{x} = x + H_1 n_1 + H_2 n_2
\end{equation}

As shown in eqref:eq:estimate_perfect_dyn, the complementary filters $H_1(s)$ and $H_2(s)$ operates only on the noise of the sensors.

Thus, this sensor fusion architecture permits to filter the noise of both sensors without introducing any distortion in the physical quantity to measure, and the estimation error $\delta x$ is described by eqref:eq:estimate_error.

#+NAME: eq:estimate_error
\begin{equation}
  \delta x = \hat{x} - x = H_1 n_1 + H_2 n_2
\end{equation}

The Power Spectral Density (PSD) of the $\delta_x$, depends both on the norms of the complementary filters and of the PSD of the noise sources eqref:eq:noise_filtering_psd.
#+NAME: eq:noise_filtering_psd
\begin{equation}
  \Phi_{\delta x} = \left|H_1\right|^2 \Phi_{n_1} + \left|H_2\right|^2 \Phi_{n_2}
\end{equation}

Usually, the two sensors have higher noise levels over distinct yet complementary frequency regions.
In order to lower the noise of the estimation $\hat{x}$, the norm $|H_i|$

The two complementary filters are used to combine the filtered noise and yield to a better estimate $\hat{x}$ over a larger bandwidth.

Thus, the noise of the super sensor is determined by the norm of the complementary filters.

** Robustness of the Fusion
<<sec:fusion_robustness>>

We considered ideal dynamics
Now let's consider error

** Upper bounds as a mathematical translation of the requirements
<<sec:requirements_upper_bounds>>

As stated above, the requirements in terms of noise attenuation and robustness of the sensor fusion architecture can be termed as upper bounds on the norm of the complementary filters.

* Complementary Filters Shaping using the $\mathcal{H}_\infty$ Synthesis
<<sec:hinf_method>>

** Introduction                                                     :ignore:
As shown in Sec. ref:sec:requirements, most of the performance requirements can be expressed as upper bounds on the magnitude of the complementary filters.

Thus, the $\mathcal{H}_\infty$ framework seems adapted and we here propose a technique to synthesis complementary filters while specifying uppers bounds on their magnitudes.

** $\mathcal{H}_\infty$ problem formulation
<<sec:hinf_synthesis>>

In this section, we formulate the synthesis of complementary filters as an $\mathcal{H}_\infty$ optimization problem.

The synthesis objective is to shape the norm of two filters $H_1(s)$ and $H_2(s)$ while ensuring their complementary property ($H_1(s) + H_2(s) = 1$).

To define the maximum allowed norm of the filters, we define two weighting transfer functions $W_1(s)$ and $W_2(s)$.

The synthesis problem is then to find stable transfer functions $H_1(s)$ and $H_2(s)$ such that
#+NAME: eq:comp_filter_problem_form
\begin{subnumcases}{}
  H_1(s) + H_2(s) = 1 \label{eq:hinf_cond_complementarity} \\
  |H_1(j\omega)| \le \frac{1}{|W_1(j\omega)|} \quad \forall\omega \label{eq:hinf_cond_hl} \\
  |H_2(j\omega)| \le \frac{1}{|W_2(j\omega)|} \quad \forall\omega \label{eq:hinf_cond_hh}
\end{subnumcases}

To express this synthesis problem into an $\mathcal{H}_\infty$ synthesis problem, we define the following generalized plant $P$ (also shown on Fig. ref:fig:h_infinity_robust_fusion):
#+NAME: eq:generalized_plant
\begin{equation}
  \colvec{w\\u} = P \colvec{z_2 \\ z_1 \\ v}; \quad P = \begin{bmatrix} W_2 & -W_2 \\ 0 & W_1 \\ 1 & 0 \end{bmatrix}
\end{equation}

#+name: fig:h_infinity_robust_fusion
#+caption: Architecture used for the $\mathcal{H}_\infty$ synthesis of complementary filters
#+attr_latex: :scale 1
[[file:figs/h_infinity_robust_fusion.pdf]]

The $\mathcal{H}_\infty$ synthesis objective is then to design a stable filter $H_1$ such that the $\mathcal{H}_\infty$ norm of the transfer function from $w$ to $[z_2, \ z_1]$ is less than $1$:
#+NAME: eq:hinf_syn_obj
\begin{equation}
  \hnorm{\begin{matrix} (1 - H_1) W_2 \\ H_1 W_1 \end{matrix}} \le 1
\end{equation}
Which is equivalent to
#+NAME: eq:hinf_problem
\begin{equation}
  \hnorm{\begin{matrix} H_2 W_2 \\ H_1 W_1 \end{matrix}} < 1 \text{ by choosing } H_2 = 1 - H_1
\end{equation}

Performance conditions eqref:eq:hinf_cond_hl and eqref:eq:hinf_cond_hl are satisfied by eqref:eq:hinf_problem.
Complementary condition eqref:eq:hinf_cond_complementarity is satisfied by design: $H_2 = 1 - H_1$ and thus $H_1 + H_2 = 1$.
The stability condition is guaranteed by the $H_\infty$ synthesis (*reference*).


Using this synthesis method, we are then able to shape at the same time the high pass and low pass filters while ensuring their complementary.

** Choice of the weighting functions
<<sec:hinf_weighting_func>>

We here give some advice on the design of the weighting functions used for the synthesis of the complementary filters using the $\mathcal{H}_\infty$ method.

However, one should be careful when designing the complementary filters, and should only use stable and minimum phase transfer functions.
The order of the weights should stay reasonably small as this will increase the complexity of the optimization problem.

Moreover, the order of the complementary filters will be equal to the sum of the order of the weighting functions used.

One should not forget the fundamental limitations imposed by the complementary property: $H_1(s) + H_1(s) = 1$.
This implies that $H_1$ and $H_2$ cannot be made small at the same time.


We here propose a formula for the design of the weighting function eqref:eq:weight_formula.

#+name: eq:weight_formula
\begin{equation}
  W(s) = \left( \frac{
           \hfill{} \frac{1}{\omega_0} \sqrt{\frac{1 - \left(\frac{G_0}{G_c}\right)^{\frac{2}{n}}}{1 - \left(\frac{G_c}{G_\infty}\right)^{\frac{2}{n}}}} s + \left(\frac{G_0}{G_c}\right)^{\frac{1}{n}}
         }{
           \left(\frac{1}{G_\infty}\right)^{\frac{1}{n}} \frac{1}{\omega_0} \sqrt{\frac{1 - \left(\frac{G_0}{G_c}\right)^{\frac{2}{n}}}{1 - \left(\frac{G_c}{G_\infty}\right)^{\frac{2}{n}}}} s + \left(\frac{1}{G_c}\right)^{\frac{1}{n}}
         }\right)^n
\end{equation}
with:
- $G_0$ is the absolute gain at low frequency
- $G_\infty$ is the absolute gain at high frequency
- $\omega_0$ and $G_c$ define the absolute value of the filter at $\omega = \omega_0$: $|W(j\omega_0)| = G_c$
- $n$ is the absolute slope of the filter, it is also equal to the order of the filter

The constrains are that $G_0 < 1 < G_\infty$ and $G_0 < G_c < G_\infty$ or that $G_\infty < 1 < G_0$ and $G_\infty < G_c < G_0$.

The shape of the weight generated using the formula is shown on Fig. ref:fig:weight_formula.

#+name: fig:weight_formula
#+caption: Amplitude of the proposed formula for the weighting functions, $G_0 = 1e^{-3}$, $G_\infty = 10$, $\omega_c = \SI{10}{Hz}$, $G_c = 2$, $n = 3$
#+attr_latex: :scale 1
[[file:figs/weight_formula.pdf]]

** Example
<<sec:hinf_example>>

We are now using the proposed $\mathcal{H}_\infty$ complementary filters synthesis method for a simple example.

The goal is to design

We use the formula eqref:eq:weight_formula for both $w_L(s)$ and $w_H(s)$.
The parameters used are summarized on table ref:tab:weights_params. And the magnitude of the weighting functions are shown on Fig. ref:fig:hinf_synthesis_results.

#+name: tab:weights_params
#+caption: Parameters used for the weighting functions
#+attr_latex: :environment tabular :width \linewidth :align |c|c|c|
#+attr_latex: :float t :placement [!htpb]
|------------------------+--------+--------|
| Parameters             | $w_L$  | $w_H$  |
|------------------------+--------+--------|
| $G_0$                  | $0.1$  | $1000$ |
|------------------------+--------+--------|
| $G_\infty$             | $1000$ | $0.1$  |
|------------------------+--------+--------|
| $\omega_c$ [$\si{Hz}$] | $11$   | $10$   |
|------------------------+--------+--------|
| $G_c$                  | $2$    | $2$    |
|------------------------+--------+--------|
| $n$                    | $2$    | $3$    |
|------------------------+--------+--------|


# #+name: fig:weights_wl_wh
# #+caption: Weighting Functions used for the $\mathcal{H}_\infty$ Synthesis
# #+attr_latex: :scale 1
# [[file:figs/weights_wl_wh.pdf]]

After synthesis, the obtain filters are:
\begin{align}
  H_L(s) &= \frac{10^{-8} (s+6.6e^9) (s+3450)^2 (s^2 + 49s + 895)}{(s+6.6e^4) (s^2 + 106 s + 3000) (s^2 + 72s + 3580)}\\
  H_H(s) &= \frac{(s+6.6e^4) (s+160) (s+4)^3}{(s+6.6e^4) (s^2 + 106 s + 3000) (s^2 + 72s + 3580)}
\end{align}

Their bode plot is shown on Fig. ref:fig:hinf_synthesis_results.

#+name: fig:hinf_synthesis_results
#+caption: Weighting functions and Obtain Complementary Filters using the $\mathcal{H}_\infty$ Synthesis
#+attr_latex: :scale 1
[[file:figs/hinf_synthesis_results.pdf]]

** Synthesis of Three Complementary Filters
<<sec:hinf_three_comp_filters>>

*** Why it is used sometimes                                       :ignore:


*** Mathematical Problem                                           :ignore:
The $\mathcal{H}_\infty$ synthesis of two complementary filters can be generalized to three or more complementary filters.

The synthesis problem is then to compute $n$ filters $H_i(s)$ such that:
#+NAME: eq:hinf_problem_gen
\begin{subequations}
  \begin{align}
  & \sum_{i=0}^n H_i(s) = 1 \label{eq:hinf_cond_compl_gen} \\
  & \left| H_i(s) \right| < \frac{1}{\left| W_i \right|}, \quad i = 1 \dots n \label{eq:hinf_cond_perf_gen}
  \end{align}
\end{subequations}

*** H-Infinity Architecture                                        :ignore:
We now propose and $\mathcal{H}_\infty$ synthesis architecture for the design of three complementary filters.

The architecture is shown on figure ref:fig:comp_filter_three_hinf

The $\mathcal{H}_\infty$ objective is:
\begin{equation}
  \left\| \begin{matrix} (1 - H_1 - H_2) W_3 \\ H_2 W_2 \\ H_1 W_1 \end{matrix} \right\|_\infty \le 1
\end{equation}

By choosing $H_3 = 1 - H_1 - H_2$, the proposed $\mathcal{H}_\infty$ synthesis solves the problem eqref:eq:hinf_problem_gen.

#+name: fig:comp_filter_three_hinf
#+caption: Architecture for the $\mathcal{H}_\infty$ synthesis of three complementary filters
#+attr_latex: :scale 1
[[file:figs/comp_filter_three_hinf.pdf]]

*** Example of generated complementary filters                     :ignore:

An example is given to validate the method where three sensors are used in different frequency bands: up to $\SI{1}{Hz}$, from $1$ to $\SI{10}{Hz}$ and above $\SI{10}{Hz}$ respectively.

Chosen weighting functions and obtained complementary filters are shown on Fig. ref:fig:hinf_three_synthesis_results.

#+name: fig:hinf_three_synthesis_results
#+caption: Obtained three complementary filters
#+attr_latex: :scale 1
[[file:figs/hinf_three_synthesis_results.pdf]]

* Application to the design of
<<sec:application_ligo>>

** Introduction                                                     :ignore:

** Specifications
<<sec:ligo_specifications>>

# #+name: fig:ligo_specifications
# #+caption: Specifications on the norms of the complementary filters
# #+attr_latex: :scale 1
# [[file:figs/ligo_specifications.pdf]]

** Weighting functions design
<<sec:ligo_weights>>

#+name: fig:ligo_weights
#+caption: Specification and Weighting Functions used for the $\mathcal{H}_\infty$ synthesis
#+attr_latex: :scale 1
[[file:figs/ligo_weights.pdf]]

** $\mathcal{H}_\infty$ Synthesis
<<sec:ligo_results>>

#+name: fig:comp_fir_ligo_hinf
#+caption: Comparison of the filters obtain with the $\mathcal{H}_\infty$ synthesis and the FIR filters designed in cite:hua05_low_ligo
#+attr_latex: :scale 1
[[file:figs/comp_fir_ligo_hinf.pdf]]

* Conclusion
  <<sec:conclusion>>

* Acknowledgment

* Bibliography                                                       :ignore:
\bibliography{ref}
