#+TITLE: Design of Complementary Filters Using $\mathcal{H}_\infty$ Synthesis
:DRAWER:
#+LATEX_CLASS: ieeeconf
#+LATEX_CLASS_OPTIONS: [letterpaper, 10 pt, conference]
#+OPTIONS: toc:nil todo:nil
#+STARTUP: overview

#+DATE: {{{time(%Y-%m-%d)}}}
#+AUTHOR: @@latex:Dehaeze Thomas\textsuperscript{1,2,$\dagger$}, Verma Mohit\textsuperscript{1,3} and Collette Christophe\textsuperscript{1,3} @@
#+AUTHOR: @@latex:\thanks{\textsuperscript{1} Precision Mechatronics Laboratory, A\&M Department, Liege, Belgium}@@
#+AUTHOR: @@latex:\thanks{\textsuperscript{2} European Synchrotron Radiation Facility, Grenoble, France}@@
#+AUTHOR: @@latex:\thanks{\textsuperscript{3} Unversité Libre de Bruxelles, BEAMS Department, Brussels, Belgium}@@
#+AUTHOR: @@latex:\thanks{\textsuperscript{$\dagger$} Corresponding Author. Email: {\tt\small thomas.dehaeze@esrf.fr}}@@

#+LATEX_HEADER: \usepackage{amsmath,amssymb,amsfonts, cases}
#+LATEX_HEADER: \usepackage[noadjust,space,compress]{cite}
#+LATEX_HEADER: \usepackage{tabularx,siunitx,booktabs}
#+LATEX_HEADER: \usepackage{algorithmic, graphicx, textcomp}
#+LATEX_HEADER: \usepackage{xcolor, import, hyperref}
#+LATEX_HEADER: \usepackage[USenglish]{babel}
#+LATEX_HEADER: \setcounter{footnote}{1}
#+LATEX_HEADER: \renewcommand{\citedash}{--}
#+LATEX_HEADER: \IEEEoverridecommandlockouts

\bibliographystyle{IEEEtran}
:END:

* Build                                                            :noexport:
#+BEGIN_SRC emacs-lisp :results none
  (add-to-list 'org-latex-classes
               '("ieeeconf"
                 "\\documentclass{ieeeconf}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
#+END_SRC

#+BEGIN_SRC emacs-lisp :results none
  (defun delete-org-comments (backend)
    (loop for comment in (reverse (org-element-map (org-element-parse-buffer)
                                      'comment 'identity))
          do
          (setf (buffer-substring (org-element-property :begin comment)
                                  (org-element-property :end comment))
                "")))

  ;; add to export hook
  (add-hook 'org-export-before-processing-hook 'delete-org-comments)
#+END_SRC

* Abstract                                                           :ignore:
#+begin_abstract
  The paper presents a design method for complementary filters using $\mathcal{H}_\infty$ synthesis that allows to specify the shape of the complementary filters norms.
  This method is shown to be easy to use and is successfully applied for the design high order complex complementary filters.
#+end_abstract

* Introduction
  <<sec:introduction>>

*** Establish the importance of the research topic                 :ignore:
# What are Complementary Filters
A set of filters is said to be complementary if the sum of their transfer functions is equal to one at all frequencies.
These filters are used when two or more sensors are measuring the same physical quantity with different noise characteristics. Unreliable frequencies of each sensors are filtered out by the complementary filters and then combined to form a super sensor giving a better estimate of the physical quantity over a wider bandwidth.
This technique is called sensor fusion and is used in many applications.\par

*** Applications of complementary filtering                        :ignore:
# Improve bandwidth for UAV
In cite:zimmermann92_high_bandw_orien_measur_contr,corke04_inert_visual_sensin_system_small_auton_helic,min15_compl_filter_desig_angle_estim, such technique is used for the attitude estimation of Unmanned Aerial Vehicles (UAV) using various sensors (accelerometers, gyroscopes, vision sensors, etc.).
# Improving the control robustness
In cite:collette15_sensor_fusion_method_high_perfor, several sensor fusion configurations using different types of sensors are discussed in order to increase the control bandwidth of active vibration isolation systems.
# Merging of different sensor types
Furthermore, sensor fusion is used in the isolation systems of the Laser Interferometer Gravitational-Wave Observator (LIGO) to merge inertial sensors with relative sensors
cite:matichard15_seism_isolat_advan_ligo,hua04_polyp_fir_compl_filter_contr_system. \par

*** Current design methods for complementary filters               :ignore:
# Why Design of Complementary Filter is important
As the super sensor noise characteristics largely depends on the complementary filter norms, their proper design is of primary importance for sensor fusion.
# Discuss the different approach to complementary filter design
In cite:corke04_inert_visual_sensin_system_small_auton_helic,jensen13_basic_uas,min15_compl_filter_desig_angle_estim, analytical formulas of complementary filters of first and second order have been proposed.
# Third Order and Higher orders
Higher order complementary filters have been used in
cite:shaw90_bandw_enhan_posit_measur_using_measur_accel,zimmermann92_high_bandw_orien_measur_contr,collette15_sensor_fusion_method_high_perfor.
# Alternate Formulation
In cite:jensen13_basic_uas, the sensitivity and complementary sensitivity transfer functions of a feedback architecture have been proposed to be used as complementary filters. The design of such filters can then benefits from the classical control theory developments.
# LMI / convex Optimization
Linear Matrix Inequalities (LMIs) are used in cite:pascoal99_navig_system_desig_using_time for the synthesis of complementary filters satisfying some frequency-like performance.
# Least Square method for finding the optimal filter coefficients
# A design method using linear least squares to optimize the coefficients of complementary filters is proposed in cite:min15_compl_filter_desig_angle_estim.
# FIR Filters
Finally, high order Finite Impulse Response (FIR) complementary filters synthesized using convex optimization is proposed in cite:hua05_low_ligo,hua04_polyp_fir_compl_filter_contr_system. \par

*** Describe a gap in the research                                 :ignore:
# There is a need for easy synthesis methods for complementary filters
Although many design methods of complementary filters have been proposed in the literature, it lacks a simple synthesis method that allows to shape the norm of the complementary filters.

*** Describe the paper itself / the problem which is addressed     :ignore:
# In this paper, we propose a synthesis method for the shaping of complementary filters using the $\mathcal{H}_\infty$ norm.\par
This paper proposes a new design method of complementary filters based on $\mathcal{H}_\infty$ synthesis extensively used in control systems.
This design method permits to easily shape the norms of the generated filters.\par

*** Introduce Each part of the paper                               :ignore:
The section ref:sec:requirements gives a brief overview of sensor fusion using complementary filters and explains how the typical requirements for such fusion are on the norms of the filters.
In section ref:sec:hinf_method, a new design method for the shaping complementary filters using $\mathcal{H}_\infty$ synthesis is proposed.
In section ref:sec:application_ligo, the method is used to design complex complementary filters that are used for sensor fusion at the LIGO.
Our conclusions are drawn in the final section.

* Complementary Filters Requirements
<<sec:requirements>>
** Sensor Fusion Architecture
<<sec:sensor_fusion>>

Let's consider two sensors measuring the same physical quantity $x$ but with dynamics $G_1(s)$ and $G_2(s)$, and with noise characteristics $n_1$ and $n_2$.

The signals from both sensors are fed into two complementary filters $H_1(s)$ and $H_2(s)$ and then combined to yield an estimate $\hat{x}$ of $x$ as shown in Fig. ref:fig:fusion_super_sensor.
#+NAME: eq:comp_filter_estimate
\begin{equation}
  \hat{x} = \left(G_1 H_1 + G_2 H_2\right) x + H_1 n_1 + H_2 n_2
\end{equation}

#+name: fig:fusion_super_sensor
#+caption: Sensor fusion architecture
#+attr_latex: :scale 1
[[file:figs/fusion_super_sensor.pdf]]

The complementary property of $H_1(s)$ and $H_2(s)$ implies that their transfer function sum is equal to one at all frequencies eqref:eq:comp_filter.
#+NAME: eq:comp_filter
\begin{equation}
  H_1(s) + H_2(s) = 1
\end{equation}

** Noise Sensor Filtering
<<sec:noise_filtering>>

Let's first consider sensors with perfect dynamics
#+name: eq:perfect_dynamics
\begin{equation}
  G_1(s) = G_2(s) = 1
\end{equation}

The estimate $\hat{x}$ is then described by
#+NAME: eq:estimate_perfect_dyn
\begin{equation}
  \hat{x} = x + H_1 n_1 + H_2 n_2
\end{equation}

From eqref:eq:estimate_perfect_dyn, the complementary filters $H_1(s)$ and $H_2(s)$ is shown to only operates on the sensors noises.
Thus, this sensor fusion architecture permits to filter the noise of both sensors without introducing any distortion in the physical quantity to be measured.

The estimation error $\delta x$ is defined by eqref:eq:estimate_error.
#+NAME: eq:estimate_error
\begin{equation}
  \delta x \triangleq \hat{x} - x = H_1 n_1 + H_2 n_2
\end{equation}

As shown in eqref:eq:noise_filtering_psd, the Power Spectral Density (PSD) of the estimation error $\Phi_{\delta x}$ depends both on the norms of the complementary filters and on the PSD of the noise sources $\Phi_{n_1}$ and $\Phi_{n_2}$.
#+NAME: eq:noise_filtering_psd
\begin{equation}
  \Phi_{\delta x} = \left|H_1\right|^2 \Phi_{n_1} + \left|H_2\right|^2 \Phi_{n_2}
\end{equation}

Usually, the two sensors have higher noise levels over distinct yet complementary frequency regions.
In order to lower the noise of the super sensor, the norm $|H_1|$ has to be made small when $\Phi_{n_1}$ is larger than $\Phi_{n_2}$ and $|H_2|$ small when $\Phi_{n_2}$ is larger than $\Phi_{n_1}$.

# Thus, the noise of the super sensor is determined by the norm of the complementary filters.

** Robustness of the Fusion
<<sec:fusion_robustness>>

In practical systems, the sensor dynamics always has some level of uncertainty and cannot be inverted perfectly such that $G_i(s) = 1$.

This uncertainty can be represented as input multiplicative uncertainty as shown in Fig. ref:fig:fusion_gain_mismatch_bis where $\Delta_i$ is any stable transfer function satisfying $\|\Delta_i(j\omega)\|_\infty \le 1,\ \forall\omega$, and $|W_i(s)|$ represents the frequency dependent uncertainty level.

#+name: fig:fusion_gain_mismatch_bis
#+caption: Sensor fusion architecture with sensor dynamics uncertainty
#+attr_latex: :scale 1
[[file:figs/fusion_gain_mismatch_bis.pdf]]

The super sensor dynamics eqref:eq:super_sensor_dyn_uncertainty is no longer equal to $1$ and it now dependent on the sensor dynamics uncertainties $W_i(s)$ as well as on the complementary filters $H_i(s)$.
#+name: eq:super_sensor_dyn_uncertainty
\begin{equation}
  \frac{\hat{x}}{x} = 1 + W_1(s) H_1(s) \Delta_1(s) + W_2(s) H_2(s) \Delta_2(s)
\end{equation}

In order to limit the phase and gain uncertainty of the super sensor, one may want to design the complementary filters such that eqref:eq:max_uncertainty_super_sensor is satisfied.
#+name: eq:max_uncertainty_super_sensor
\begin{equation}
  \begin{aligned}
    & \left|W_1 H_1 \Delta_1\right| + \left|W_2 H_2 \Delta_2\right| \le \epsilon \quad \forall\omega,\ \forall \Delta_i\\
    \Leftrightarrow & \left|W_1 H_1\right| + \left|W_2 H_2\right| \le \epsilon \quad \forall\omega
  \end{aligned}
\end{equation}

Condition eqref:eq:max_uncertainty_super_sensor is equivalent as bounding the uncertainty set of the super sensor dynamics in the complex plane by a circle centered at $1$ with a radius equal to $\epsilon$ (Fig. ref:fig:uncertainty_gain_phase_variation_bis).

#+name: fig:uncertainty_gain_phase_variation_bis
#+caption: Uncertainty set of the super sensor dynamics
#+attr_latex: :scale 1
[[file:figs/uncertainty_gain_phase_variation_bis.pdf]]

The maximum phase added by the super sensor uncertainty $\Delta\phi$ is then equal to eqref:eq:max_phase_uncertainty.
#+name: eq:max_phase_uncertainty
\begin{equation}
    \Delta \phi = \arcsin\left( \epsilon \right)
\end{equation}

Limiting the phase added by the super sensor to $\Delta \phi = \SI{30}{\degree}$ requires that $H_1(s)$ and $H_2(s)$ are designed such that eqref:eq:max_uncertainty_super_sensor is satisfied with $\epsilon = \sin(\Delta\phi = \SI{30}{\degree}) = 0.5$.
Thus the norm of the complementary filter $|H_i|$ for sensor $i$ should be made small at frequencies where its dynamic uncertainty $|W_i|$ is large.\par

As stated above, the requirements in terms of noise performance and robustness of the sensor fusion architecture can be seen as upper bounds on the norm of the complementary filters.

* Complementary Filters Shaping using $\mathcal{H}_\infty$ Synthesis
<<sec:hinf_method>>
** Introduction                                                     :ignore:
As shown in Sec. ref:sec:requirements, most of the performance requirements for the design of the complementary filters can be expressed as upper bounds on the magnitude of the filters.
Therefore, the $\mathcal{H}_\infty$ Loop Shaping framework is adapted such synthesis problem.
In this section, a technique for the synthesis complementary filters while specifying uppers bounds on their magnitudes using $\mathcal{H}_\infty$ synthesis is presented.

** Synthesis of Complementary Filters as a $\mathcal{H}_\infty$ problem
<<sec:hinf_synthesis>>

The synthesis objective is to shape the norm of two filters $H_1(s)$ and $H_2(s)$ while ensuring their complementary property eqref:eq:comp_filter.

The synthesis problem is then to find stable transfer functions $H_1(s)$ and $H_2(s)$ such that conditions eqref:eq:comp_filter_problem_form are satisfied.
#+NAME: eq:comp_filter_problem_form
\begin{subequations}
  \begin{align}
  & H_1(s) + H_2(s) = 1 \label{eq:hinf_cond_complementarity} \\
  & |H_1(j\omega)| \le \frac{1}{|W_1(j\omega)|} \quad \forall\omega \label{eq:hinf_cond_h1} \\
  & |H_2(j\omega)| \le \frac{1}{|W_2(j\omega)|} \quad \forall\omega \label{eq:hinf_cond_h2}
  \end{align}
\end{subequations}
where $W_1(s)$ and $W_2(s)$ are two weighting transfer functions chosen to shape the corresponding filters.

In order to express this optimization problem as a standard $\mathcal{H}_\infty$ problem, the standard architecture shown in Fig. ref:fig:h_infinity_robust_fusion is used where the generalized plant $P$ is described by eqref:eq:generalized_plant.
#+NAME: eq:generalized_plant
\begin{equation}
  \begin{bmatrix} z_1 \\ z_2 \\ v \end{bmatrix} = P(s) \begin{bmatrix} w\\u \end{bmatrix}; \quad P(s) = \begin{bmatrix}W_1(s) & -W_1(s) \\ 0 & W_2(s) \\  1 & 0 \end{bmatrix}
\end{equation}

#+name: fig:h_infinity_robust_fusion
#+caption: Architecture used for $\mathcal{H}_\infty$ synthesis of complementary filters
#+attr_latex: :scale 1
[[file:figs/h_infinity_robust_fusion.pdf]]

The $\mathcal{H}_\infty$ filter design problem is then to find a stable filter $H_2(s)$ which based on $v$, generates a signal $u$ such that the $\mathcal{H}_\infty$ norm from $w$ to $[z_1, \ z_2]$ is less than one eqref:eq:hinf_syn_obj.
#+NAME: eq:hinf_syn_obj
\begin{equation}
  \left\|\begin{matrix} \left[1 - H_2(s)\right] W_1(s) \\ H_2(s) W_2(s) \end{matrix}\right\|_\infty \le 1
\end{equation}

Which is equivalent to eqref:eq:hinf_problem by defining $H_1(s) \triangleq 1 - H_2(s)$.
#+NAME: eq:hinf_problem
\begin{equation}
  \left\|\begin{matrix} H_1(s) W_1(s) \\ H_2(s) W_2(s) \end{matrix}\right\|_\infty \le 1
\end{equation}

The complementary condition eqref:eq:hinf_cond_complementarity is ensured by the definition of $H_1(s)$. The conditions eqref:eq:hinf_cond_h1 and eqref:eq:hinf_cond_h2 on the shape of the filters are satisfied by eqref:eq:hinf_problem.

Using this method based on $\mathcal{H}_\infty$ synthesis, the complementary filters can be shaped as wanted.

** Choice of the weighting functions
<<sec:hinf_weighting_func>>

The choice of the weighting functions is of primary importance for the success of the presented $\mathcal{H}_\infty$ synthesis of complementary filters.

First, only proper, stable and minimum phase transfer functions should be used.
Second, the order of the weights should stay reasonably small as this will increase both the complexity of the optimization problem and the order of the synthesized complementary filters, the latter being equal to the sum of the weighting functions orders.
Third, one should not forget the fundamental limitations imposed by the complementary property: $H_1(s) + H_2(s) = 1$.
This implies for instance that $|H_1(j\omega)|$ and $|H_2(j\omega)|$ cannot be made small at the same time.


# Explain why we propose such weighting function
When designing complementary filters, it is usually desired to specify the slope of the filter, its crossover frequency and its gain at low and high frequency.
To help with the design of the weighting functions such that the above specification are easily expressed, the following formula is proposed.
#+name: eq:weight_formula
\begin{equation}
  W(s) = \left( \frac{
           \hfill{} \frac{1}{\omega_0} \sqrt{\frac{1 - \left(\frac{G_0}{G_c}\right)^{\frac{2}{n}}}{1 - \left(\frac{G_c}{G_\infty}\right)^{\frac{2}{n}}}} s + \left(\frac{G_0}{G_c}\right)^{\frac{1}{n}}
         }{
           \left(\frac{1}{G_\infty}\right)^{\frac{1}{n}} \frac{1}{\omega_0} \sqrt{\frac{1 - \left(\frac{G_0}{G_c}\right)^{\frac{2}{n}}}{1 - \left(\frac{G_c}{G_\infty}\right)^{\frac{2}{n}}}} s + \left(\frac{1}{G_c}\right)^{\frac{1}{n}}
         }\right)^n
\end{equation}
where:
- $G_0$ is the absolute gain at low frequency
- $G_\infty$ is the absolute gain at high frequency
- $\omega_0$ and $G_c$ define the magnitude of the filter at $\omega_0$: $|W(j\omega_0)| = G_c$
- $n$ is the order of the weighting function which is also equal to its slope between high and low frequency

The parameters $G_0$, $G_c$ and $G_\infty$ should either satisfy condition eqref:eq:cond_formula_1 or eqref:eq:cond_formula_2.
#+NAME: eq:condition_params_formula
\begin{subequations}
  \begin{align}
    G_0 < 1 < G_\infty \text{ and } G_0 < G_c < G_\infty \label{eq:cond_formula_1}\\
    G_\infty < 1 < G_0 \text{ and } G_\infty < G_c < G_0 \label{eq:cond_formula_2}
  \end{align}
\end{subequations}

The shape of the weighting function generated using eqref:eq:weight_formula is shown in Fig. ref:fig:weight_formula.

#+name: fig:weight_formula
#+caption: Amplitude of the proposed formula eqref:eq:weight_formula, $G_0 = 1e^{-3}$, $G_\infty = 10$, $\omega_c = \SI{10}{Hz}$, $G_c = 2$, $n = 3$
#+attr_latex: :scale 1
[[file:figs/weight_formula.pdf]]

** Example
<<sec:hinf_example>>

Let's validate the proposed design method of complementary filters using $\mathcal{H}_\infty$ synthesis with a simple example.

Both weighting functions $W_1(s)$ and $W_2(s)$ are designed using eqref:eq:weight_formula.
The parameters used are summarized in table ref:tab:weights_params and the magnitude of the weighting functions are shown in Fig. ref:fig:hinf_synthesis_results.

The blending frequency is chosen to be $\SI{10}{Hz}$. The slope of $|H_1(j\omega)|$ is set to $-2$ above $\SI{10}{Hz}$ by choosing $n=2$ for $W_1(s)$. The slope of $|H_2(j\omega)|$ is set to $+3$ below $\SI{10}{Hz}$ by choosing $n=3$ for $W_2(s)$. The order of the obtained complementary filters will thus be equal to $5$.

#+name: tab:weights_params
#+caption: Parameters used for $W_1(s)$ and $W_2(s)$
#+ATTR_LATEX: :environment tabularx :width 0.5\linewidth :align Xcc
#+ATTR_LATEX: :center t :booktabs t :float t
| Parameter              | $W_1(s)$ | $W_2(s)$ |
|------------------------+----------+----------|
| $G_0$                  | $0.1$    | $1000$   |
| $G_\infty$             | $1000$   | $0.1$    |
| $\omega_c$ [$\si{Hz}$] | $11$     | $10$     |
| $G_c$                  | $2$      | $2$      |
| $n$                    | $2$      | $3$      |

The bode plots of the obtained complementary filters are shown in Fig. ref:fig:hinf_synthesis_results and their transfer functions in the Laplace domain are given below.
\begin{align*}
  H_1(s) &= \frac{10^{-8} (s+6.6e^9) (s+3450)^2 (s^2 + 49s + 895)}{(s+6.6e^4) (s^2 + 106 s + 3e^3) (s^2 + 72s + 3580)}\\
  H_2(s) &= \frac{(s+6.6e^4) (s+160) (s+4)^3}{(s+6.6e^4) (s^2 + 106 s + 3e^3) (s^2 + 72s + 3580)}
\end{align*}

#+name: fig:hinf_synthesis_results
#+caption: Frequency response of the weighting functions and complementary filters obtained using $\mathcal{H}_\infty$ synthesis
#+attr_latex: :scale 1
[[file:figs/hinf_synthesis_results.pdf]]

** Generalization to the synthesis of Three Complementary Filters
<<sec:hinf_three_comp_filters>>

*** Why it is used sometimes                                       :ignore:
Some applications may require to merge more than two sensors.
In such case, it is necessary to design as many complementary filters $H_i(s)$ as the number of sensors used.

*** Mathematical Problem                                           :ignore:
The synthesis problem is then to compute $n$ stable transfer functions $H_i(s)$ such that eqref:eq:hinf_problem_gen is satisfied.
#+NAME: eq:hinf_problem_gen
\begin{subequations}
  \begin{align}
  & \sum_{i=0}^n H_i(s) = 1 \label{eq:hinf_cond_compl_gen} \\
  & \left| H_i(j\omega) \right| < \frac{1}{\left| W_i(j\omega) \right|}, \quad \forall \omega,\ i = 1 \dots n \label{eq:hinf_cond_perf_gen}
  \end{align}
\end{subequations}

*** H-Infinity Architecture                                        :ignore:
The synthesis architecture in Fig. ref:fig:h_infinity_robust_fusion can be generalized for the synthesis of a set of $n$ complementary filters.
For the synthesis of three complementary filters, the architecture used is shown in Fig. ref:fig:comp_filter_three_hinf.

The $\mathcal{H}_\infty$ synthesis objective applied on $P(s)$ is to design two stable filters $H_2(s)$ and $H_3(s)$ such that the $\mathcal{H}_\infty$ norm of the transfer function from $w$ to $[z_1,\ z_2, \ z_3]$ is less than one eqref:eq:hinf_syn_obj_three.
#+name: eq:hinf_syn_obj_three
\begin{equation}
  \left\| \begin{matrix} \left[1 - H_2(s) - H_3(s)\right] W_1(s) \\ H_2(s) W_2(s) \\ H_3(s) W_3(s) \end{matrix} \right\|_\infty \le 1
\end{equation}

#+name: fig:comp_filter_three_hinf
#+caption: Architecture for $\mathcal{H}_\infty$ synthesis of three complementary filters
#+attr_latex: :scale 1
[[file:figs/comp_filter_three_hinf.pdf]]

By choosing $H_1(s) \triangleq 1 - H_2(s) - H_3(s)$, the proposed $\mathcal{H}_\infty$ synthesis solves the design problem eqref:eq:hinf_problem_gen. \par

*** Example of generated complementary filters                     :ignore:
An example is given to validate the method where three sensors are used in different frequency bands (up to $\SI{1}{Hz}$, from $1$ to $\SI{10}{Hz}$ and above $\SI{10}{Hz}$ respectively).
Three weighting functions are designed using eqref:eq:weight_formula and shown by dashed curves in Fig. ref:fig:hinf_three_synthesis_results.
The obtained complementary filters after synthesis are shown in Fig. ref:fig:hinf_three_synthesis_results.

#+name: fig:hinf_three_synthesis_results
#+caption: Frequency response of the weighting functions and three complementary filters obtained using $\mathcal{H}_\infty$ synthesis
#+attr_latex: :scale 1
[[file:figs/hinf_three_synthesis_results.pdf]]

* Application: Design of Complementary Filters used in the Active Vibration Isolation System at the LIGO
<<sec:application_ligo>>
** Introduction                                                     :ignore:
Several complementary filters are used in the active isolation system at the LIGO cite:hua05_low_ligo,hua04_polyp_fir_compl_filter_contr_system.
The requirements on those filters are very tight and thus their design is complex.
The approach used in cite:hua05_low_ligo for their design is to write the synthesis of complementary FIR filters as a convex optimization problem.
The obtained FIR filters are compliant with the requirements. However they are of very high order so their implementation is quite complex.

The effectiveness of the proposed method is demonstrated by designing complementary filters with the same requirements as described in cite:hua05_low_ligo.

** Complementary Filters Specifications
<<sec:ligo_specifications>>
The specifications for one pair of complementary filter used at the LIGO are summarized below (for further details, refer to cite:hua04_polyp_fir_compl_filter_contr_system):
- From $0$ to $\SI{0.008}{Hz}$, the magnitude of the filter's transfer function should be less or equal to $8 \times 10^{-4}$
- Between $\SI{0.008}{Hz}$ to $\SI{0.04}{Hz}$, the filter should attenuate the input signal proportional to frequency cubed
- Between $\SI{0.04}{Hz}$ to $\SI{0.1}{Hz}$, the magnitude of the transfer function should be less than $3$
- Above $\SI{0.1}{Hz}$, the magnitude of the complementary filter should be less than $0.045$

The specifications are represented by the dashed black curves on the bode plot in Fig. ref:fig:ligo_weights.

** Weighting Functions Design
<<sec:ligo_weights>>
The weighting functions should be designed such that their inverse amplitude is as close as possible to the specifications in order to not over-constrain the synthesis problem.
However, the order of the filters should be reasonably small in order to reduce the computational costs of the optimization problem and for physical implementation of the filters.

A Type I Chebyshev filter of order $20$ is used as the weighting transfer function corresponding to the low pass filter $w_L(s)$. For the one corresponding to the high pass filter $w_H(s)$, a $7^{\text{th}}$ order transfer function is designed.
The magnitudes the weighting functions inverses are shown in Fig. ref:fig:ligo_weights.

#+name: fig:ligo_weights
#+caption: Specification and weighting functions used for $\mathcal{H}_\infty$ synthesis
#+attr_latex: :scale 1
[[file:figs/ligo_weights.pdf]]

** $\mathcal{H}_\infty$ Synthesis
<<sec:ligo_results>>
$\mathcal{H}_\infty$ synthesis is performed using the architecture shown in Fig. ref:eq:generalized_plant.
The complementary filters obtained are of order $27$.
In Fig. ref:fig:comp_fir_ligo_hinf, their bode plot is compared with the FIR filters of order 512 obtained in cite:hua05_low_ligo.

#+name: fig:comp_fir_ligo_hinf
#+caption: Comparison of the FIR filters (solid) designed in cite:hua05_low_ligo with the filters obtained with $\mathcal{H}_\infty$ synthesis (dashed)
#+attr_latex: :scale 1
[[file:figs/comp_fir_ligo_hinf.pdf]]

* Conclusion
  <<sec:conclusion>>
This paper has shown how complementary filters can be used to combine multiple sensors in order to obtain a super sensor.
Typical specification on the super sensor noise and on the robustness of the sensor fusion has been shown to be linked to the norms of the complementary filters.
Therefore, a synthesis method that permits the shaping of the complementary filters norms has been proposed and has been successfully applied for the design of complex filters.
Future work will aim at further developing this synthesis method for the robust and optimal synthesis of complementary filters used in sensor fusion.

* Acknowledgment
This research benefited from a FRIA grant from the French Community of Belgium.

* Bibliography                                                       :ignore:
\bibliography{ref}
